# Generated by Django 5.2.1 on 2025-05-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='duracion_dias',
            new_name='numero_integrantes',
        ),
    ]
